version: '3'
services:
  postgres:
    image: postgres:11.6-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: tubecrown
      POSTGRES_USER: tubecrown_postgres
      POSTGRES_PASSWORD: tubecrown_secret
    ports:
      - 5432:5432
  watch:
    image: tubecrown/dev-nodejs
    volumes:
      - .:/usr/src/app
    command: npm run watch
  api:
    depends_on:
      - watch
      - postgres
    restart: on-failure
    image: tubecrown/dev-nodejs
    volumes:
      - .:/usr/src/app
    command: npm run dev-api
    ports:
      - 4100:4100
  web:
    depends_on:
      - watch
      - api
    restart: on-failure
    image: tubecrown/dev-nodejs
    volumes:
      - .:/usr/src/app
    command: npm run dev-web
    ports:
      - 4000:4000
volumes:
  postgres_data:
